/**
 * Intelligent Language Selector (ILS)
 * Analyzes natural language queries and selects the best programming language/adapter.
 */

const { v4: uuidv4 } = require('uuid');

class ILS {
    constructor() {
        this.rules = [
            { keywords: ['fast', 'performance', 'system', 'low-level'], language: 'cpp' },
            { keywords: ['visualize', 'plot', 'graph', 'data science', 'pandas'], language: 'python' },
            { keywords: ['web', 'server', 'api', 'json', 'async'], language: 'node' },
            { keywords: ['enterprise', 'robust', 'scale'], language: 'java' },
            { keywords: ['script', 'automation', 'shell'], language: 'bash' },
            { keywords: ['math', 'matrix', 'calculation'], language: 'matlab' },
            { keywords: ['statistics', 'analysis'], language: 'r' },
            { keywords: ['game', 'lua'], language: 'lua' },
            { keywords: ['ios', 'apple'], language: 'swift' },
            { keywords: ['android'], language: 'kotlin' },
            { keywords: ['safe', 'memory'], language: 'rust' },
            { keywords: ['concurrent', 'goroutine'], language: 'go' },
            { keywords: ['functional'], language: 'haskell' },
            { keywords: ['windows', '.net'], language: 'csharp' }
        ];
    }

    /**
     * Analyze a query and generate a UDM task
     * @param {string} query 
     * @returns {object} UDM Task
     */
    analyze(query) {
        const lowerQuery = query.toLowerCase();
        let selectedLanguage = 'python'; // Default
        let maxScore = 0;

        for (const rule of this.rules) {
            let score = 0;
            for (const keyword of rule.keywords) {
                if (lowerQuery.includes(keyword)) {
                    score++;
                }
            }
            if (score > maxScore) {
                maxScore = score;
                selectedLanguage = rule.language;
            }
        }

        console.log(`[ILS] Selected ${selectedLanguage} for query: "${query}"`);

        return {
            model_version: "5.0",
            task_type: "compute", // Default to compute for generated tasks
            language: selectedLanguage,
            target: {
                function: "generated_task",
                // In a real system, we would generate code here using an LLM
                file: ""
            },
            data: {
                query: query,
                note: "Task generated by ILS"
            },
            context: {
                source: "ILS",
                timestamp: new Date().toISOString()
            }
        };
    }
}

module.exports = new ILS();
